version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1401:1433
      
  api:
    build: ./Banco.Backend
    ports:
      - 5000:80
    links:
      - db
    depends_on:
      - db
  docs:
    build: ./api-documentacao
    ports:
      - 3000:3000
    depends_on:
      - api